### ISSUE TITLE
What happened?

### ISSUE THREAD

**Issue by ghost** [kosshishub/Quicksave-BD-plugin#1]
I need this plugin :(

**Comment by kosshi-net** [comment]
Everything you need to know is in the readme.

You still can try installing it and it might work. Just copy the file "Quicksave.plugin.js" to BetterDiscords plugin folder.

**Comment by ghost** [comment]
I actually got it to install by changing getAuthor/getName/getDescription, but I can't get the Quicksave directory to save using the save & apply button. Is there a way I can add it manually in the code?

edit: 
After adding my directory at [line 102](https://github.com/kosshishub/Quicksave-BD-plugin/blob/master/Quicksave.plugin.js#L98-L106), the plugin disappears from BetterDiscords plugin settings.

``` Javascript
Quicksave.prototype.settingsVersion = 5;
Quicksave.prototype.defaultSettings = function () {
  return {
    version: this.settingsVersion,
    direcotry: "none",
    norandom: true,
    fnLength: 4
  };
};
```
