### ISSUE TITLE
Not working at all as of 19/1/ 

### ISSUE THREAD

**Issue by petitbambi** [kosshishub/Quicksave-BD-plugin#10]
Restarted discord today and after reinstalling betterdiscord version 3.0 and making sure the quicksave plugin is still in the folder and activated in the discord tab, I can't get the icon to show up whatsoever and can't save any images. Previous to that I was also experiencing the bug of the icons not appearing but the little grey box showing up and saving images. Currently I'm not getting the grey box or any icons and can't save anything. This plugin is the only reason i got BD and it's extremely useful to me so I'd love to see it back in action soon !

**Comment by kosshi-net** [comment]
Fixed. Sorry about the slow updates.

**Comment by petitbambi** [comment]
Thank you for the update !
While it's nice to see it functioning again and actually saving images even from links and in full size & quality, I'd still really love it even if there was an optional version that kept the little grey box just because it allows for 1 click saving and it was available in the 'search' directory in servers (discord doesn't open images or allow right clicking in the search column), since I use this plugin to mass-save images off a server the difference between doing 1 click in the search column or having to jump back in chat, open image, save image, makes quite a difference ! 

I understand that takes extra time and effort to make but theres nothing that mimics the original way this plugin functioned and it was the most useful and wonderful thing I've found for the app !

**Comment by kosshi-net** [comment]
Few others wanted it back as well, didn't realize people loved it that much. Re-implemented it in my own way.

**Comment by petitbambi** [comment]
Thank you soooo much, 10000% perfect now !
