### ISSUE TITLE
Not working with BandagedDiscord (April28th) 

### ISSUE THREAD

**Issue by petitbambi** [kosshishub/Quicksave-BD-plugin#15]
My discord updated on April 28th completely breaking BetterDiscord and not making it load whatsoever, I found out that most people are using 'bandaged better discord' (https://github.com/rauenzi/BetterDiscordApp) which indeed, made it work again.
But even tho it says it loads the quicksave plugin and I can see it in my settings, quicksave is not showing any of it 's save buttons on any images. Not in servers, not in private conversations.
This could absolutely be a problem on my end but I'd really love to find the root of the problem and fix it. I've tried using an older version of quicksave (2.3, currently using 2.5) and when starting up it says it loads them but their functions dont appear. 
Made sure they are turned on and turned them off and back on, restarted discord, the buttons still aren't showing up on any images. 
Thank you for your time and hard work !

**Comment by nekosaurus** [comment]
Not working on my end either. Discord devs have been actively killing BetterDiscord plugins lately over the past couple weeks. Most of my plugins are broken now.

**Comment by xFears** [comment]
Same issue here, most of my plugins died.

**Comment by kosshi-net** [comment]
Discord renamed all of the classes again. Fixed.

**Comment by petitbambi** [comment]
Thank you tons !
