### ISSUE TITLE
Cannot Set Quicksave Directory

### ISSUE THREAD

**Issue by Zwei2234** [kosshishub/Quicksave-BD-plugin#17]
Pretty self-explanatory, based off of the title. I cannot set the quick-save directory in the "Plugins" tab of Bandaged-BetterDiscord. The plugin drop-down for Quicksave v0.2.5 does work, although "Save & Apply" does not.

Whenever I attempt to set the directory to my meme folder, which is located at "C:\Users\USER\Downloads\memes" and close the drop-down tab (or otherwise go back to normal Discord browsing), the Directory resets to its usual "none". I have pressed "Save & Apply" and have gotten the "Saved & Applied!" message replacement. I have tried doing this multiple times with Discord having both elevated permissions and not-elevated permissions.

I am using BBD v0.2.2, based off of BD v0.3.0. 

Otherwise, I believe the plugin is working. I get the "Save" button, although it says "Dir Error" for obvious reasons.

**Comment by kosshi-net** [comment]
Confirmed.

The issue is in Zere's fork, he accidentally broke BdPluginStorage. A patch to it should be pushed in a few moments.
