### ISSUE TITLE
First image always saves as image's filename

### ISSUE THREAD

**Issue by MildPanda** [kosshishub/Quicksave-BD-plugin#18]
![discord_lx943em0f2](https://user-images.githubusercontent.com/5686244/48677843-dc7d7580-eb2f-11e8-9817-9d2f1cc938f6.png)
These are my settings if that matters any. Still happens when I change the filename length to a shorter name.

Of course this isn't much of an issue but when you save a file it will always save as the file's name unless it has been saved before and in your save location. This issue may cause conflicts when moving images to a more organized location if you had already moved a file there with the same generic name.

**Comment by kosshi-net** [comment]
The random naming was completetly broken all this time ... Note to self: Test!
