### ISSUE TITLE
Invalid Character

### ISSUE THREAD

**Issue by ayyyylmao54** [kosshishub/Quicksave-BD-plugin#6]
Whenever I try to add the plugin, I get this error message. I'm not sure if it's because of the code or because of something I'm doing wrong though. I'm rather new to using betterdiscord and plugins. Any help at all would be appriciated.

![error](https://user-images.githubusercontent.com/34893138/34387255-0b82f124-eafb-11e7-9243-707343a77bcd.png)

**Comment by kosshi-net** [comment]
You don't need to run the script, just leave it in the folder and start discord.
