### ISSUE TITLE
Messes up the look of Discord.

### ISSUE THREAD

**Issue by Johnnycyan** [kosshishub/Quicksave-BD-plugin#7]
I couldn't for a while figure out what was causing this to happen. I asked the discord server for my theme and had someone look through everything and it looked fine to them. So I started disabling plugins one by one and when I got to this one it went away. So something that is in this plugin is causing it to do this. See the screen shot below to see what I'm talking about. White bar at the bottom, pushing everything up, cutting off the buttons on the top right, misaligning the lines of the different sections etc.

![image](https://user-images.githubusercontent.com/24556317/34757572-2890f658-f5a0-11e7-87c3-d5ea9f76f8fc.png)

**Comment by kosshi-net** [comment]
I removed some css added in pull #2, the plugin shouldn't affect styles right now. This issue probably isn't relevant anymore anyway, so i'll close this.
