### ISSUE TITLE
Broken Quicksave Icon

### ISSUE THREAD

**Issue by nekosaurus** [kosshishub/Quicksave-BD-plugin#8]
Don't know when this happened exactly, but the 3 mixtape.moe links used for the icon save button (the one where you simply hover over a picture and not when you actually click on it) are broken. I believe mixtape.moe had some issues in the past week that were "resolved", but the links are still broken. The picture still saves when you click on it but it stays as a gray square. I was wondering if it would be possible to reupload them to a different site or something. Thanks in advance.

**Comment by kosshi-net** [comment]
"Fixed" by removing the icon completetly. It was added in pull #2. Too complex to maintain for what it's worth. 

Sorry for the slow updates.

(EDIT: The icons functionality was reimpilemented in commit d98eabd, uses text now )
